package cerror

const (
	BAD_REQUEST           = "BAD_REQUEST"
	UNAUTHORIZED          = "UNAUTHORIZED"
	FORBIDDEN             = "FORBIDDEN"
	NOT_FOUND             = "NOT_FOUND"
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
)

const (
	SMS_CANNOT_SENT           = "SMS_CANNOT_SENT"
	INVALID_CONFIRMATION_CODE = "INVALID_CONFIRMATION_CODE"
	PHONE_USED                = "PHONE_USED"
	PHONE_BLOCKED             = "PHONE_BLOCKED"
	CODE_SENT                 = "CODE_SENT"
	USERNAME_USED             = "USERNAME_USED"
	USERNAME_INVALID          = "USERNAME_INVALID"
	PASSWORD_TOO_SHORT        = "PASSWORD_TOO_SHORT"
)
